query main {
  factories(first: 5){
    id
    name
    stakeFee
    safuFee
    teamFee
    undMinted
  }
  vaults(first: 5) {
    id
    factory
    txCount
    tvl
    volume
    cr
    LTV
    fee
    stakeFee
    limit
    token0 {
      id
      name
      symbol
    }
    token1 {
      id
      name
      symbol
    }
  }
}


