query main {
  protocol(id: "unbound") {
    id
    undMinted
  }
  factories(first: 5) {
    id
    name
    stakeFee
    safuFee
    teamFee
  }
  vaults(first: 5) {
    id
    factory
    txCount
    undMinted
    tvl
    volume
    cr
    LTV
    fee
    stakeFee
    limit
    token0 {
      id
      name
      symbol
    }
    token1 {
      id
      name
      symbol
    }
  }
}
